### ISSUE TITLE
Locality policies section in k8s doc is outdated

### ISSUE THREAD

**Issue by ddpolyakov** [LINBIT/linbit-documentation#15]
in doc everything about locality is based on localStoragePolicy parameter, but due to 0.7.0 changelog - its been removed. Doc should be updated.

**Comment by WanzenBug** [comment]
Better late than never: the volume locality settings have gone though a lot of changes in the meantime. The docs should be accurate now: https://github.com/LINBIT/linbit-documentation/blob/master/UG9/en/kubernetes.adoc#placementpolicy
