### ISSUE TITLE
Port Assignment

### ISSUE THREAD

**Issue by iomari** [LINBIT/linbit-documentation#34]
Greetings,
Can the default ports of the client and controller be changed. They are conflicting with another service.

**Comment by rck** [comment]
This is not a documentation issue. Feel free to open an issue at https://github.com/linbit/linstor-server . I'd assume chances that we change them are almost 0 as that would require many many projects to change. Maybe ask at the conflicting project :upside_down_face:

**Comment by rck** [comment]
Ah, reading your issue in linstor-server I guess this was a misunderstand. I thought you want us to change the defaults, but you actually wanted to change the port numbers from their defaults...

**Comment by iomari** [comment]
np
