### ISSUE TITLE
Misspelled word in the documentation

### ISSUE THREAD

**Issue by samuelfusato** [LINBIT/linbit-documentation#41]
Hi,

I am not sure if this is the right place to report this but can you please review the below phrase in the paragraph 5.17.2:

![image](https://user-images.githubusercontent.com/32580217/188186354-d6fd85b8-c9c5-4b9b-b17b-e2d28aa942e3.png)

Note the word _siutaions_.

Here is the link of this part in the documentation:

https://linbit.com/drbd-user-guide/users-guide-drbd-8-4/#5.17.2.%20Automatic%20split%20brain%20recovery%20policies

Thank you,
Samuel

**Comment by emteelb** [comment]
Thanks for reporting. This has been corrected in [the HTML version on LINBIT website](https://linbit.com/drbd-user-guide/users-guide-drbd-8-4/#s-automatic-split-brain-recovery-configuration).
