### ISSUE TITLE
Unable to install DRBD9 with LINSTOR on PROXMOX. Expired repos  

### ISSUE THREAD

**Issue by Softlution2** [LINBIT/linbit-documentation#46]
I have been trying for days to find out the best practices of installing DRBD with Linstor on my Proxmox cluster. I am reading the documentation and I am totally lost. 
I have a 2 node cluster (node1 , node2) and I installed a Linstor Controller within a container in node2.

The repo urls I found online are not working and I managed to download from
https://linbit.com/linbit-software-download-page-for-linstor-and-drbd-linux-driver/#linstor 
to install from source code DRBD, UTILS,  PROXMOX Connector and Linstor Controller.  I created Pools, VG and LV. The SATELLITES were active on both nodes but the resources were ''inactive (dead)''.  I am unable to create RESOURCES due to this error

''Satellite 'node2' does not support the following layers: [DRBD]''

I uninstalled the SATELLITE to reinstall but I am unable to install the SATELLITE  because the repo urls are not working and the ones they do are only for Linstor Clients. I need a free option for my homelab. Please let me know how can I make it work.

**Comment by rck** [comment]
why are [these](https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-proxmox-installing-from-linbit-public-repos) not working? what is "expired"? what is the content of your `linbit.list`? what PVE version are you using? what is the exact error message you get when you `apt update`? please help us to help you, "does not work" is nothing we could help with without any details. Also I doubt that the repos are not working, we have many users that use these repos, I guess someone would have complained earlier, but if you provide some details I will look into it.

**Comment by Softlution2** [comment]
Thanks for your reply. 
Here is the content of my libit.list. I managed to install the following but I am not sure if I am missing something. I have created  Resources and Volumes but they do not appear in the controller lists. 

I have installed the following. Please let me know if i have to add or remove something.

ii  drbd-dkms                            9.2.4-1                        all          RAID 1 over TCP/IP for Linux module source
ii  drbd-utils                           9.24.0-1                       amd64        RAID 1 over TCP/IP for Linux (user utilities)
ii  linstor-satellite                    1.23.0-1                       all          DRBD distributed resource management utility
ii  linstor-proxmox                      7.0.1-1                        all          DRBD distributed resource management utility

I have a 2 node Proxmox cluster. DRBD is inactive unless I start it manually. Should it be active in my case or not? I Also  created Resource Group, Resources and Volumes but they do not appear in the controller lists.  I followed this guide https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2FMicinka%2FProxmox%2Ftree%2Fmain%2FLinstor%3Ffbclid%3DIwAR1VywKW7a1i7O2KVHcV_UVJNkVV4TX9ETV0_J3i-CKQyK4tzBn2FEg7gjE&h=AT2MBRsoVkBVkOfAw4Ut9n61QJT6j5PEzFitmBM-yxh4zMjbogY9dfWRHv_ZGPmcTzN0-FV7HZunAMlE8OK5YVJ4DxoyYKDbGT5aW8WEXUMcN5RpyAvr93CttLJNz9QEMZ3zfA.                                                                                    

POOLS
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool          ┊ Node  ┊ Driver   ┊ PoolName      ┊ FreeCapacity ┊ TotalCapacity ┊ CanSnapshots ┊ State ┊ SharedName ┊
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ DfltDisklessStorPool ┊ node1 ┊ DISKLESS ┊               ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ node2 ┊ DISKLESS ┊               ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ zfs_pool             ┊ node1 ┊ ZFS      ┊ linstor_zpool ┊   899.25 GiB ┊       928 GiB ┊ True         ┊ Ok    ┊            ┊
┊ zfs_pool             ┊ node2 ┊ ZFS      ┊ linstor_zpool ┊   899.25 GiB ┊       928 GiB ┊ True         ┊ Ok    ┊            ┊
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


RESOURCES
╭────────────────────────────────────────────────────────────────╮
┊ ResourceName ┊ Node ┊ Port ┊ Usage ┊ Conns ┊ State ┊ CreatedOn ┊
╞════════════════════════════════════════════════════════════════╡
╰────────────────────────────────────────────────────────────────╯

VOLUMES
──────────────────────────────────────────────────────────────────────────────────────────╮
┊ Node ┊ Resource ┊ StoragePool ┊ VolNr ┊ MinorNr ┊ DeviceName ┊ Allocated ┊ InUse ┊ State ┊
╞══════════════════════════════════════════════════════════════════════════════════════════╡



/etc/pve/storage.cfg

lvmthin: local-lvm
        thinpool data
        vgname pve
        content rootdir,images

dir: local
        path /var/lib/vz
        content rootdir,images,backup,iso,vztmpl,snippets
        prune-backups keep-all=1


drbd: linstor_VMs
    content images,rootdir
    controller node1,node2
    resourcegroup linstor_VMs
