### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by vic-t** [LINBIT/linbit-documentation#51]
See https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-kubernetes-drbd-options-setting-on-node-connection

The link pointing to "protocol A" is pointing to a file:// URL.

**Comment by rck** [comment]
fixed in https://github.com/LINBIT/linbit-documentation/commit/d9e0167779e05c84ac2a630f497f15cfb73c3d91
